### ISSUE TITLE
Daikin firmware update breaks indoor temp readout

### ISSUE THREAD

**Issue by extric99** [DirtyDevWork/homebridge-daikin#21]
Daikin released a new firmware update (1.2.51) several weeks ago that breaks the indoor room temperature readout. Since the firmware update all indoor temps are 0,0. The rest of the functionality seems to unaffected and continous to work fine

**Comment by extric99** [comment]
I reinstalled the homebrdige container and now nothing is working anymore

http://192.168.0.30/aircon/get_sensor_info 
http://192.168.0.30/aircon/get_control_info

all above urls return valid info if i try them manually  but in the logfile only see

Error getting state: null
getTemperatureDisplayUnits: 0
getTargetHeatingCoolingState: 0
etc

**Comment by mafa915** [comment]
Yes, same here. No functionality on the devices that I updated. 
Any fixes?

**Comment by ronzelver** [comment]
Same here after updating the firmware to v1.2.51. No readout of temperature nor any control functions are working. 
The output of get_sensor_info and get_control_info are still working in the browser:

ret=OK,htemp=23.0,hhum=-,otemp=3.0,err=0,cmpfreq=48,mompow=7

ret=OK,pow=1,mode=4,adv=,stemp=21.0,shum=0,dt1=25.0,dt2=M,dt3=22.0,dt4=21.0,dt5=21.0,dt7=25.0,dh1=AUTO,dh2=50,dh3=0,dh4=0,dh5=0,dh7=AUTO,dhh=50,b_mode=4,b_stemp=21.0,b_shum=0,alert=255,f_rate=5,f_dir=0,b_f_rate=5,b_f_dir=0,dfr1=5,dfr2=5,dfr3=7,dfr4=5,dfr5=5,dfr6=5,dfr7=5,dfrh=5,dfd1=0,dfd2=0,dfd3=0,dfd4=0,dfd5=0,dfd6=0,dfd7=0,dfdh=0,dmnd_run=0,en_demand=0

**Comment by cbrandlehner** [comment]
same problem here

**Comment by cbrandlehner** [comment]
Daikin Firmware 1.2.51 is responding differently to HTTP request. With this version, the host parameter is now case sensitive. The 'request' library sends the http request using 'host' while a browser would use 'Host'.  
This has also been discussed here: [https://community.athom.com/t/daikin-ai/158/34](https://community.athom.com/t/daikin-ai/158/34)

**Comment by extric99** [comment]
@cbrandlehner thanks for debugging. 
As I am not technical i have no idea if this is something that can be correct by a technical ‘volunteer’. My coding skills are non existent and it would be a shame to let this plugin go to waste

**Comment by kennyadsl** [comment]
Same issue here. 

@cbrandlehner I can't find in the `request` library source code where `HOST` is used instead of `Host` by default, at least in master.

**Comment by ronzelver** [comment]
I think I saw some lines converting strings to uppercase, that might be the cause of this behavior?!

**Comment by kennyadsl** [comment]
@ronzelver did you see those lines on this project?

**Comment by ronzelver** [comment]
No, in the 'request' library.

**Comment by cbrandlehner** [comment]
I forked this project and adapted it for the new firmware.
https://github.com/cbrandlehner/homebridge-daikin-local

**Comment by ronzelver** [comment]
Thanks Christian, my Daikin is responding correctly again with you fork! 👍🏼👍🏼👍🏼
