### ISSUE TITLE
Unable to push commands to Daikin

### ISSUE THREAD

**Issue by DirtyDevWork** [DirtyDevWork/homebridge-daikin#9]
Can read sensor values and what mode the Daikin is in, but can't push commands to the Daikin

**Comment by icepicknz** [comment]
I can concur I can read details; don't see outside temperature only inside; not that it really matters but for automation may be good to say "If x degrees outside and you have aircon on, might be best to open a window" or something haha

**Comment by travellingnashes** [comment]
Yep 0.11 works for read as described in #8

**Comment by DirtyDevWork** [comment]
Improved somewhat, now crafting commands for Daikin correctly, but appear to be missing a parameter as the Daikin system reports back a PARAM NG (or No Go)
I'll be setting up a sniffer on my network so I can peek at what the official app is doing specifically

I'll pop open an extra issue for reading Outside Temp sensor, although it looks like I'll need to display that to HomeKit as a separate accessory (though if you find another way to do it let me know). It'll be part of the "[Integrate Additional Features](https://github.com/DirtyDevWork/homebridge-daikin/projects/2)" project that I'll commence working on once the main commands work! :)

**Comment by DirtyDevWork** [comment]
@icepicknz Just added Issue #10 for you

**Comment by DirtyDevWork** [comment]
So I've got it down to the minimum parameters needed for the Daikin to accept a command:
`/aircon/set_control_info?pow=0&mode=4&stemp=23.0&shum=0`
Sending this from a web browser's URL bar works, but when sending exactly the same via Homebridge, we still get the PARAM NG response.

Promising, pretty sure I'm just missing one or two headers.

**Comment by DirtyDevWork** [comment]
Got it, now works like a charm!

Well, ish.
But that completes the Basic Func project, the Daikin can now be controlled via HimeBridge and HomeKit!
